### ISSUE TITLE
Incorrect behavior if minimumValue or maximumValue are changed

### ISSUE THREAD

**Issue by DrummerB** [cbpowell/CPSlider#7]
Hi,

If I change the minimumValue or maximumValue of the CPSlide, it doesn't seem to work correctly. The first time I move my finger/mouse after touching the slider, the value jumps to the left.

Steps to reproduce:
1. In the Demo project, add these lines in CPViewController, after the CPSlider was initialized:
`slider.minimumValue = 50;`
`slider.maximumValue = 150;`
2. Start the app. Slide the slider to the right. Let go. Try to slide it again. Slider should jump to the left for some reason.

**Comment by cbpowell** [comment]
Good catch, thanks. Fixed it in [release 1.1.1](https://github.com/cbpowell/CPSlider/releases/tag/1.1.1). The  code that calculates the new value was correctly normalizing to the min/max value, but it wasn't shifting by the minimum value.

**Comment by DrummerB** [comment]
Wow, that was fast. Thanks a lot!
